version: '3.4'
services:
  app:
    build:
      context: .
      dockerfile: DevDockerfile
    environment:
      - CHOKIDAR_USEPOLLING=true
    ports:
      - 8080:8080
      - 6006:6006
    volumes:
      - ..:/app:cached
      - ptapp_node_modules:/app/node_modules

  #   # Overrides default command so things don't shut down after the process ends.
    command: /bin/sh -c "while sleep 1000; do :; done"

volumes:
  # Volume for api node_modules
  ptapp_node_modules:


